title:              Igor
tagline:            Lima
description:        Blog sobre assuntos tech, mercado de trabalho, academia, e diversos :)
url:                http://limasigor2.github.io

author:
  name:             Igor Lima
  url:              https://linkedin.com/in/limasigor2
  email:            limasigor2@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
